### ISSUE TITLE
Question About Pair Trading Code

### ISSUE THREAD

**Issue by PanggNOTlovebean** [je-suis-tm/quant-trading#11]
Pair trading backtest.py Line 89:
`signals['fitted']=np.mat(sm.add_constant(signals['asset2']))*np.mat(model.params).reshape(2,1)`
Why assets2 became an independent variable at this time？But  Can see that it is the dependent variable in regression model.
`   x=sm.add_constant(train['asset1'])
    y=train['asset2']
    model=sm.OLS(y,x).fit()
`
I tried to exchange them but got worse results，I know your code is right,but i wanna know more abot this,why such two variable can be exchanged here?
THX!!!!!!!!!!!!!!!!!!!

**Comment by je-suis-tm** [comment]
Hi PanggNOTlovebean

Thank you for pointing the exchange out.
Actually I was wrong and you are right.
The only reason your exchange made things worse is because I messed up the signal as well.
This is apparently an oversight, two wrongs don't make one right, lol

I have updated the script to correct this error.
I have slightly changed the structure as well.
Now the cointegration test is on a rolling basis.

Again, thanks for pointing out the existing error.

T.M.
