### ISSUE TITLE
Just trying to reach out

### ISSUE THREAD

**Issue by rich1488** [je-suis-tm/quant-trading#41]
Hey I hate doing it like this but your email (je-suis-tm@yandex.com) listed on the contact section of your website didn't work.

I'm sure you're very busy but still wanted to reach out because you only miss the shots you don't take, as i always say. Would you be interested in contributing to this momentum signal idea I have? Even if you could just grace us with a few hours per week or whenever you have ome downtime to spare. We would greatly appreciate.

We're just a small group of young developers (most high school) age working on a social trading app that mainly operates on Discord right now. I won't go into specifics right now as it's not relevant. But I do want to clarify that we can't compensate you for our time as we don't have the capital or the revenue to offer you a fair rate.

I know this is a long shot but just had to try, you seem to be full of knowledge with technical analysis and indicators so you would be perfect for this project.

Thanks for your time

**Comment by je-suis-tm** [comment]
Hi rich1488, thanks for reaching out. As you can see, I am not updating this repository very often. Unfortunately I am fully occupied by other aspects of work/life so I won't be able to help you. Since you guys are young and into trading, my advice is simple. You either do well in math and follow the quant track into a big institutions with better bid ask spread or be well connected to the bankers to obtain information advantage. Do a sharpe ratio calc on your time and effort. You may be getting rich faster if you switch your trading time to coding for a promising startup or just FANG. If you can work in Bay area, why waste your time with wall street?

**Comment by gwonchan** [comment]
He is AI hahahahahaha
